### ISSUE TITLE
ServletContext resource [/keyspaces-application.conf] cannot be resolved to URL because it does not exist

### ISSUE THREAD

**Issue by dvDevelopment** [aws-samples/amazon-keyspaces-examples#37]
Hi everybody, 

After I added **spring-boot-starter-web** dependency to my pom.xml, unfortunately it does not start anymore. It can not find config file.

_Exception message_
`Caused by: java.lang.IllegalStateException: Failed to load cassandra configuration from ServletContext resource [/keyspaces-application.conf]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.loadConfig(CassandraAutoConfiguration.java:148) ~[spring-boot-autoconfigure-2.7.4.jar:2.7.4]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraConfiguration(CassandraAutoConfiguration.java:136) ~[spring-boot-autoconfigure-2.7.4.jar:2.7.4]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.lambda$cassandraDriverConfigLoader$1(CassandraAutoConfiguration.java:126) ~[spring-boot-autoconfigure-2.7.4.jar:2.7.4]
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder.lambda$build$2(DefaultProgrammaticDriverConfigLoaderBuilder.java:251) ~[java-driver-core-4.14.1.jar:na]
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultDriverConfigLoader.<init>(DefaultDriverConfigLoader.java:196) ~[java-driver-core-4.14.1.jar:na]
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultDriverConfigLoader.<init>(DefaultDriverConfigLoader.java:182) ~[java-driver-core-4.14.1.jar:na]
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultProgrammaticDriverConfigLoaderBuilder.build(DefaultProgrammaticDriverConfigLoaderBuilder.java:244) ~[java-driver-core-4.14.1.jar:na]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraDriverConfigLoader(CassandraAutoConfiguration.java:128) ~[spring-boot-autoconfigure-2.7.4.jar:2.7.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	... 93 common frames omitted
Caused by: java.io.FileNotFoundException: ServletContext resource [/keyspaces-application.conf] cannot be resolved to URL because it does not exist
	at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:174) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.loadConfig(CassandraAutoConfiguration.java:145) ~[spring-boot-autoconfigure-2.7.4.jar:2.7.4]
	... 105 common frames omitted`

Do you know what could be a problem?

Google says nothing about it.

**Comment by dvDevelopment** [comment]
Problem ist solved with adding **"classpath:"** to the name of conf file. 

Example:
`spring.data.cassandra.config=classpath:keyspaces-application.conf`
